/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Collection__factory } from "./Collection__factory";
export { Dwin__factory } from "./Dwin__factory";
